### PR TITLE
fix: add date types to ArrowHelper

### PR DESCRIPTION
**Pull request by spieden**
https://github.com/cloudquery/cloudquery/issues/15431

### CODE REVIEW

**Comment by candiduslynx** [comment]
@spieden thanks for the contribution!

Could you also add the code to test date types to https://github.com/cloudquery/plugin-sdk-java/blob/main/lib/src/test/java/io/cloudquery/helper/ArrowHelperTest.java (or to the same test package)?

**Review by candiduslynx — COMMENTED** [review]
Looks good, but I'd love to also see tests added for this

**Comment by spieden** [comment]
@candiduslynx Ok done. I removed the `DateMilliVector` support because it was failing round trips and I'm not using it anyway. (Values go in as longs and come out as some kind of DateTime.)

**Review by candiduslynx — APPROVED** [review]

**Comment by candiduslynx** [comment]
@spieden the build for the ci workflow fails

**Comment by spieden** [comment]
@candiduslynx Hmm, fixed locally but not getting a status back 🤔

**Pull request merged**
